policy_path: "{LEGGED_GYM_ROOT_DIR}/deploy/pre_train/irmv2/policy_1.pt"
onnx_policy_path: "{LEGGED_GYM_ROOT_DIR}/deploy/deploy_real/irmv2_policy.onnx"
xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/irmv_v2/scene.xml"

# Total simulation time
simulation_duration: 1000.0
# Simulation time step
simulation_dt: 0.002
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 10

kps: [100, 100, 200, 200, 20, 100, 100, 200, 200, 20]
kds: [2, 2, 4, 4, 2, 2, 2, 4, 4, 2]

default_angles: [0.0,  0.0,  -0.4363,  0.7854, -0.3491,
                  0.0,  0.0,  -0.4363,  0.7854, -0.3491]

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 10
num_obs: 39
frame_stack: 10

cmd_init: [0, 0, 0]

log_name: "data_irmv2.csv"